github: [metadata]
highlighter: none
url: https://otherness-space.github.io/spring-demo-materialize-scss
# url: http://localhost:4000

timezone: America/New_York

# Handling Reading
encoding: UTF-8

incremental: true

excerpt_separator: <!--more-->

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  jailed: false
  gfm_quirks: paragraph_end
# enable_analytics: true

script:
  - JEKYLL_ENV=production bundle exec jekyll build

# Where things are
posts:
    output: true

plugins:
  # default
  # - jekyll-coffeescript
  # - jekyll-gist
  # - jekyll-github-metadata
  # - jekyll-paginate
  - jekyll-relative-links
  # - jekyll-optional-front-matter
  # - jekyll-readme-index
  # - jekyll-default-layout
  # - jekyll-titles-from-headings
  # optional
  - jekyll-feed
  # - jekyll-redirect-from
  # - jekyll-seo-tag
  # - jekyll-sitemap
  # - jekyll-avatar
  # - jemoji
  - jekyll-mentions
  # - jekyll-include-cache

sass:
  load_paths:
    - scss
    # - sass_dir
    # - _sass
    # - node_modules
  style: compressed

# Handling Reading
encoding: utf-8

include:
  - permalink: /404.html
  - assets/js

exclude:
  - node_modules
  # - LICENSE
  - Makefile
  # - README.md
  - package.json
  - package-lock.json
  - yarn.lock
  - blank.html
  - assets/css/blank.css
  - assets/css/add-style.css
  - test
  - .eslintrc.js
  - .travis.yml
  - index.js
  - assets/css/prism.css
  # - assets/css/style.css
  - assets/js/prism.js
  # - assets/js/script.js
